objects/copado__ExtensionConfiguration__c.object
<CustomObject>
    <description>Defines the configuration for a specific extension.</description>
    <fields>
        <fullName>copado__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__ExtensionApplication__c</fullName>
        <inlineHelpText>Select the Copado Phase based on the Extension Tool you want to use. For example, if you select Test, the Extension Tool picklist will list the available Tools for that specific phase, e.g. Copado Robotic Test, Apex tests, or SCA tools such as PMD or Codescan.</inlineHelpText>
        <label>Copado Phase</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__ExtensionTool__c</fullName>
        <label>Extension Tool</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual Tests</fullName>
                </value>
                <value>
                    <fullName>Apex Tests</fullName>
                </value>
                <value>
                    <fullName>PMD</fullName>
                </value>
                <value>
                    <fullName>Pull Request</fullName>
                </value>
                <value>
                    <fullName>Checkmarx</fullName>
                </value>
                <value>
                    <fullName>sfdx-scanner</fullName>
                </value>
                <value>
                    <fullName>Flow Tests</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Deprecated</description>
        <label>Status - Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Setup Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Extension Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extension Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Error_Message__c</fullName>
        <description>Description of the error if the job has failed.</description>
        <inlineHelpText>Description of the error if the job has failed.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__JobStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
        <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</inlineHelpText>
        <label>Job Step</label>
        <referenceTo>copado__JobStep__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Job_Type__c</fullName>
        <description>API name of the job that triggered the result. This information can be used for reporting purposes.</description>
        <inlineHelpText>API name of the job that triggered the result. This information can be used for reporting purposes.</inlineHelpText>
        <label>Job API Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Progress_Status__c</fullName>
        <description>This status is used to track the current job activity.</description>
        <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
        <label>Progress Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>Status of the job execution.</description>
        <inlineHelpText>Status of the job execution.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Test parent object which triggered the execution.</description>
        <inlineHelpText>The Test parent object which triggered the execution.</inlineHelpText>
        <label>Test</label>
        <referenceTo>copado__Test__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/copado_labs__EvaluateScanResultTest.cls
@isTest
public class EvaluateScanResultTest {
    @isTest
    private static void executeSingleTest() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan Non-QG' LIMIT 1];

            // Exercise 
            new EvaluateScanResult().execute(null, jobStepResult, 'Success');
            
            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan' AND copado__Test__c != null LIMIT 1];
            System.assertEquals('Success', testResult.copado__Status__c, 'The test result should not be Failed');
            System.assertEquals('Success', testResult.copado__Progress_Status__c, 'The progress status should not be Failed');
        }
    }
    @isTest
    private static void executeSingleTestFailure() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan Non-QG' LIMIT 1];

            // Exercise 
            new EvaluateScanResult().execute(null, jobStepResult, 'Failed');
            
            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan' AND copado__Test__c != null LIMIT 1];
            System.assertEquals('Failed', testResult.copado__Status__c, 'The test result should be Failed');
            System.assertEquals('Failed', testResult.copado__Progress_Status__c, 'The progress status should be Failed');
        }
    }

    @isTest
    private static void executeQg() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan QG' LIMIT 1];
            
            // Exercise 
            new EvaluateScanResult().execute(null, jobStepResult, 'Success');

            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan' AND copado__Test__c = null LIMIT 1];
            System.assertEquals('Success', testResult.copado__Status__c, 'The test result should not be Failed');
            System.assertEquals('Success', testResult.copado__Progress_Status__c, 'The progress status should not be Failed');
        }
    }
    
    @isTest
    private static void executeQgFailure() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan QG' LIMIT 1];
            
            // Exercise 
            new EvaluateScanResult().execute(null, jobStepResult, 'Failed');

            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = 'CodeScan' AND copado__Test__c = null LIMIT 1];
            System.assertEquals('Failed', testResult.copado__Status__c, 'The test result should be Failed');
            System.assertEquals('Failed', testResult.copado__Progress_Status__c, 'The progress status should be Failed');
        }
    }

    @isTest
    private static void executeException() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            //Setup
            String errorMessage = 'Attempt to de-reference a null';

            // Exercise 
            Exception ex;
            try {
                new EvaluateScanResult().execute(null, null, 'Success');
            } catch (Exception e) {
                ex = e;
            }

            // Verify
            System.assertEquals(true, ex.getMessage().contains(errorMessage), 'The exception message matches.');
        }
    }

    @TestSetup
    private static void makeData() {
        User runAsUser = new User(
            LastName = 'UserLastName',
            Username = 'username@myemail.com',
            Email = 'username@myemail.com',
            Alias = 'MyAlias',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = UserInfo.getProfileId(),
            LanguageLocaleKey = 'en_US'
        );
        insert runAsUser;
        
        System.runAs(runAsUser) {
            copado.GlobalAPI copadoGlobalAPI = new copado.GlobalAPI();
            copado.GlobalAPI.UserLicense userLicense = new copado.GlobalAPI.UserLicense();
            userLicense.isCCMEnabled = true;
            userLicense.isCopadoEnabled = true;
            userLicense.userId = runAsUser.Id;
            copadoGlobalAPI.upsertCopadoLicense(userLicense);
            
            PermissionSetAssignment copado = new PermissionSetAssignment();
            copado.PermissionSetId = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Copado_User' LIMIT 1].Id;
            copado.AssigneeId = runAsUser.Id;
    
            insert copado;

        
            copado__ExtensionConfiguration__c extensionConfiguration = new copado__ExtensionConfiguration__c(copado__Active__c = true, copado__ExtensionTool__c = 'Manual Tests', copado__ExtensionApplication__c = 'Test');
            insert extensionConfiguration;

            copado__Test__c testItem1 = new copado__Test__c(Name = 'CodeScan Test - Single Execution', copado__ExtensionConfiguration__c = extensionConfiguration.Id, copado__ReadyToRun__c = true);
            copado__Test__c testItem2 = new copado__Test__c(Name = 'CodeScan Test - QG Execution', copado__ExtensionConfiguration__c = extensionConfiguration.Id, copado__ReadyToRun__c = true);
            List<copado__Test__c> tests = new List<copado__Test__c>{testItem1, testItem2};
            insert tests;

            copado__Result__c testResult = new copado__Result__c(copado__Test__c = testItem1.Id, copado__Job_Type__c = 'CodeScan', copado__Status__c = 'Not Started');
            copado__Result__c qGResult = new copado__Result__c(copado__Job_Type__c = 'CodeScan', copado__Status__c = 'Not Started');
            List<copado__Result__c> pmdTestResults = new List<copado__Result__c>{testResult, qGResult};
            insert pmdTestResults;

            copado__JobTemplate__c template = new copado__JobTemplate__c(Name = 'Run CodeScan', copado__Version__c = 1);
            insert template;
        
            copado__JobExecution__c execution1 = new copado__JobExecution__c(
                copado__Template__c = template.Id,
                copado__DataJson__c = '{"resultIds" : [ "'+ testResult.Id +'" ]}'
            );
            copado__JobExecution__c execution2 = new copado__JobExecution__c(
                copado__Template__c = template.Id,
                copado__DataJson__c = '{"resultId" : "'+ qGResult.Id +'"}'
            );
            List<copado__JobExecution__c> executions = new List<copado__JobExecution__c>{execution1, execution2};
            insert executions;

            copado__JobStep__c jobStep1 = new copado__JobStep__c(Name = 'Evaluate CodeScan Result', copado__JobExecution__c = execution1.Id, copado__Type__c = 'Function');
            copado__JobStep__c jobStep2 = new copado__JobStep__c(Name = 'Evaluate CodeScan Result', copado__JobExecution__c = execution2.Id, copado__Type__c = 'Function');
            List<copado__JobStep__c> jobSteps = new List<copado__JobStep__c>{jobStep1, jobStep2};
            insert jobSteps;

            copado__Result__c jobStepResult1 = new copado__Result__c(copado__Job_Type__c = 'CodeScan Non-QG', copado__JobStep__c = jobStep1.Id, copado__Status__c = 'Success');
            copado__Result__c jobStepResult2 = new copado__Result__c(copado__Job_Type__c = 'CodeScan QG', copado__JobStep__c = jobStep2.Id, copado__Status__c = 'Success');
            List<copado__Result__c> results = new List<copado__Result__c>{jobStepResult1, jobStepResult2};
            insert results;
        }
    }
}