objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Function__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the function that triggered the result.</description>
        <inlineHelpText>Lookup field to the function that triggered the result.</inlineHelpText>
        <label>Function</label>
        <referenceTo>copado__Function__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__JobStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
        <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</inlineHelpText>
        <label>Job Step</label>
        <referenceTo>copado__JobStep__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Progress_Status__c</fullName>
        <description>This status is used to track the current job activity.</description>
        <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
        <label>Progress Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>Status of the job execution.</description>
        <inlineHelpText>Status of the job execution.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/copado_labs__EvaluateScanResult.cls
global with sharing class EvaluateScanResult implements copado.MCCallback{

    global void execute(copado__Function__c function, copado__Result__c result, String status) {
        try {
            // If there are other intermediary statuses passed into this class ignore them
            if (status == 'Success' || status == 'Failed') {
                Set<Id> resultIdsToUpdate = getResultIdsFrom(result.Id);
                updateResults(resultIdsToUpdate,status);
            }
        } catch (Exception ex) {
            throw new EvaluateScanResultException(ex.getMessage() + '' + ex.getStackTraceString());
        }
    }

    //PRIVATE

    private Set<Id> getResultIdsFrom(Id resultId) {
        Set<Id> result = new Set<Id>();

        String jobExecutionPayload = [SELECT copado__JobStep__r.copado__JobExecution__r.copado__DataJson__c 
                                      FROM copado__Result__c 
                                      WHERE Id= :resultId LIMIT 1][0].copado__JobStep__r.copado__JobExecution__r.copado__DataJson__c;
        JobExecutionPayload jobPayload = (JobExecutionPayload) System.JSON.deserialize(jobExecutionPayload, JobExecutionPayload.class);
		
        if (jobPayload.resultId != null) { // Consolidated result is not null
            result.add((Id) jobPayload.resultId);
        } else if (jobPayload.resultIds != null) { // Consolidated result is null but there are individual results
            result.addAll((List<Id>) jobPayload.resultIds);
        }

        return result;
    }

    private void updateResults(Set<Id> resultIdsToUpdate, String status){
        List<copado__Result__c> results = [SELECT copado__Status__c, copado__Progress_Status__c
                                              FROM copado__Result__c 
                                              WHERE Id IN :resultIdsToUpdate];

        for (copado__Result__c result : results) {
            String finalStatus = status == 'Success' ? 'Success' : 'Failed';

            result.copado__Status__c = finalStatus;
            result.copado__Progress_Status__c = finalStatus;
        }
        if (Schema.sObjectType.copado__Result__c.isUpdateable()) {
            update results;
        }

    }
    public with sharing class EvaluateScanResultException extends Exception{}
    // INNER CLASS
	
    private class JobExecutionPayload {
        private String resultId;
        private List<String> resultIds;
    }
}